steps:
  # 1. Ottieni un Access Token valido usando l'immagine SDK di Google
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth print-access-token > /workspace/access_token

  # 2. Installa le gemme usando il token per l'autenticazione
  - name: 'ruby:3.2'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Leggi il token
        access_token=$(cat /workspace/access_token)
        
        # Configura Bundler (variabili minuscole per evitare sostituzioni Cloud Build)
        registry_host="europe-west1-ruby.pkg.dev"
        
        echo "Configuro auth per $registry_host..."
        bundle config set --global "https://$registry_host" "oauth2accesstoken:$access_token"

        # Installa
        bundle install --jobs=4 --retry=3

  # 3. Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy send-sms-function \
        --gen2 \
        --region=europe-west1 \
        --runtime=ruby32 \
        --source=. \
        --entry-point=send_sms \
        --trigger-http \
        --allow-unauthenticated \
        --set-secrets=TWILIO_ACCOUNT_SID=twilio-account-sid:latest,TWILIO_AUTH_TOKEN=twilio-auth-token:latest,TWILIO_FROM_NUMBER=twilio-from-number:latest

timeout: '300s'
options:
  logging: CLOUD_LOGGING_ONLY
